### ISSUE TITLE
Outdated elements can be added as dataElementGroup members

### ISSUE THREAD

**Issue by ammarbarakat** [mig-frankfurt/dataelementhub.gui#36]
**Describe your problem.**

Outdated elements can be added as dataElementGroup members.

**If it is a bug name steps to reproduce**

1. Go to 'Create dataElementGroup dialog'
2. Go to add members field
3. OUTDATED elements can be added as members

**If it is a bug complete the following information:**

- Version: Until commit 8cceac0b70e680ac6e1586a8847256f3b3bb38ea
- OS: Windows
- Browser: Firefox

**Describe the solution you'd like**

Disable adding outdated elements as members.

**Additional context**

**Comment by vabishaa** [comment]
Issue was fixed in #56 DataElementGroup members are not visible in the update dialog
